### ISSUE TITLE
Errors while running tests

### ISSUE THREAD

**Issue by bolelamx** [mikekucherov/studytube-assignment#3]
Hi @mikekucherov,
I couldn't run tests, there are some errors. Could you check and fix them please?

![Screenshot from 2022-03-24 13-09-10](https://user-images.githubusercontent.com/14018755/159904364-4dff5f1f-666a-4b1c-bff3-8637d5be7461.png)

**Comment by mikekucherov** [comment]
Hi @bolelamx . Done! Sorry for delay
